[adguard_lxc]
adguard-basilisk ansible_host=10.0.0.124 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/ansible_basilisk

[app_lxc]
debian-basilisk ansible_host=10.0.0.30 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/ansible_basilisk

[proxy_lxc]
proxy-basilisk ansible_host=10.0.0.121 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/ansible_basilisk

[searxng_lxc]
searxng-basilisk ansible_host=10.0.0.126 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/ansible_basilisk

[test_lxc]
#test-proxy-basilisk ansible_host=10.0.0.251 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/ansible_basilisk
#test-adguard-basilisk ansible_host=10.0.0.250 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/ansible_basilisk

[tor_lxc]
tor-basilisk ansible_host=10.0.0.2 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/ansible_basilisk

[vaultwarden_lxc]
vaultwarden-basilisk ansible_host=10.0.0.125 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/ansible_basilisk

[wireguard_lxc]
wireguard-basilisk ansible_host=10.0.0.123 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/ansible_basilisk

[frigate_lxc]
frigate-basilisk ansible_host=10.0.0.122 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/ansible_basilisk

