bind_host: 0.0.0.0

admin_port: 3000
dns_port: 53
https_port: 443
http_port: 80

admin_user: admin
admin_password_hash: "{{ adguard_tmp-user_password_hash }}" 

upstream_dns:
  - https://security.cloudflare-dns.com/dns-query
  - https://dns10.quad9.net/dns-query
 # - tls://1.1.1.1
 # - tls://8.8.8.8

bootstrap_dns:
  - 9.9.9.9
  - 1.1.1.1
  - 149.112.112.10

#blocked_services:
#  - facebook
#  - tiktok

parental_enabled: false
safesearch_enabled: false
safe_browsing_enabled: true
querylog_enabled: true
querylog_size: 10000
statistics_enabled: true
cache_size: 4194304
ratelimit: 20
blocking_mode: default
enable_https: false
tls_cert: ""
tls_key: ""
enable_dhcp: false
dhcp_interface:
dhcp_gateway:
dhcp_subnet:
dhcp_start:
dhcp_end:
dhcp_lease:

filters:
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt

  - enabled: true
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.txt

rewrites:
  - domain: search.basilisk.home
    answer: 10.0.0.121
    enabled: true
  - domain: photos.basilisk.home
    answer: 10.0.0.121
    enabled: true
  - domain: vault.basilisk.home
    answer: 10.0.0.121
    enabled: true

custom_rules:
  - "||example.com^"
