#!/usr/bin/python3

import argparse
import subprocess
import json
import ast


def tor_stats(user, ip):
    result = subprocess.run(
        ["ssh", "-i", "/home/darshak/.ssh/darshak", "-o", "StrictHostKeyChecking=accept-new", "-o", "BatchMode=yes", "{}@{}".format(user, ip), "python3", "/home/darshak/code.py"],
        capture_output=True,
        text=True,
        #check=True,
    )

    tor_stats = ast.literal_eval(result.stdout)
    #print("Return code:", result.returncode)
    #print("STDOUT:")
    print(json.dumps(tor_stats))
    #print("STDERR:")
    #print(result.stderr)

def main():
    parser = argparse.ArgumentParser(
        description="Script to retrieve status and statistics of any service."
    )

    parser.add_argument(
        "-s", "--server",
        type=str,
        help="Server to retrieve stats of."
    )
    parser.add_argument(
        "-x", "--xelp",
        action="store_true",
        help="Server to retrieve stats of."
    )

    args = parser.parse_args()
    user = "darshak"
    servers = {
        "basilisk_tor": "10.0.0.14",
        "basilisk_debian": "10.0.0.30",
        "basilisk_wireguard": "10.0.0.213"
    }

    if args.server in servers:
        tor_stats(user, servers[args.server])
    elif args.server == host_wireguard:
        pass

if __name__ == "__main__":
    main()
