Nickname    {{ tor_nickname }}
ContactInfo {{ tor_contact_info }}
ORPort      {{ tor_or_port }}
ExitRelay   0
SocksPort   0
RelayBandwidthBurst {{ bw_burst }} MBytes
ControlPort {{ ctrl_port }}
CookieAuthentication 1
